# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/centos-7.0-64-puppet"

  config.vm.network "private_network", ip: "192.168.33.34"

  config.vm.synced_folder "../shared/web", "/var/www/myproject", create: true

  config.vm.hostname = "mpwar16"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Scripts
  config.vm.provision "shell", path: "scripts/install_modules.sh", args: "/vagrant/modules/"

  # Puppet
    config.vm.provision :puppet do |puppet|
      puppet.environment_path = "environments"
      puppet.environment      = "development"
      puppet.module_path      = "modules"
    end
end